namespace Bistix
{
    public class Rates
    {
        public double Aed { get; set; }
        public double Afn { get; set; }
        public double All { get; set; }
        public double Amd { get; set; }
        public double Ang { get; set; }
        public double Aoa { get; set; }
        public double Ars { get; set; }
        public double Aud { get; set; }
        public double Awg { get; set; }
        public double Azn { get; set; }
        public double Bam { get; set; }
        public double Bat { get; set; }
        public double Bbd { get; set; }
        public double Bch { get; set; }
        public double Bdt { get; set; }
        public double Bgn { get; set; }
        public double Bhd { get; set; }
        public double Bif { get; set; }
        public double Bmd { get; set; }
        public double Bnd { get; set; }
        public double Bob { get; set; }
        public double Brl { get; set; }
        public double Bsd { get; set; }
        public double Bsv { get; set; }
        public double Btc { get; set; }
        public double Btn { get; set; }
        public double Bwp { get; set; }
        public double Byn { get; set; }
        public double Byr { get; set; }
        public double Bzd { get; set; }
        public double Cad { get; set; }
        public double Cdf { get; set; }
        public double Chf { get; set; }
        public double Clf { get; set; }
        public double Clp { get; set; }
        public double Cnh { get; set; }
        public double Cny { get; set; }
        public double Cop { get; set; }
        public double Crc { get; set; }
        public double Cuc { get; set; }
        public double Cve { get; set; }
        public double Czk { get; set; }
        public double Dai { get; set; }
        public double Djf { get; set; }
        public double Dkk { get; set; }
        public double Dop { get; set; }
        public double Dzd { get; set; }
        public double Eek { get; set; }
        public double Egp { get; set; }
        public double Eos { get; set; }
        public double Ern { get; set; }
        public double Etb { get; set; }
        public double Etc { get; set; }
        public double Eth { get; set; }
        public double Eur { get; set; }
        public double Fjd { get; set; }
        public double Fkp { get; set; }
        public double Gbp { get; set; }
        public double Gel { get; set; }
        public double Ggp { get; set; }
        public double Ghs { get; set; }
        public double Gip { get; set; }
        public double Gmd { get; set; }
        public double Gnf { get; set; }
        public double Gtq { get; set; }
        public double Gyd { get; set; }
        public double Hkd { get; set; }
        public double Hnl { get; set; }
        public double Hrk { get; set; }
        public double Htg { get; set; }
        public double Huf { get; set; }
        public double Idr { get; set; }
        public double Ils { get; set; }
        public double Imp { get; set; }
        public double Inr { get; set; }
        public double Iqd { get; set; }
        public double Isk { get; set; }
        public double Jep { get; set; }
        public double Jmd { get; set; }
        public double Jod { get; set; }
        public double Jpy { get; set; }
        public double Kes { get; set; }
        public double Kgs { get; set; }
        public double Khr { get; set; }
        public double Kmf { get; set; }
        public double Krw { get; set; }
        public double Kwd { get; set; }
        public double Kyd { get; set; }
        public double Kzt { get; set; }
        public double Lak { get; set; }
        public double Lbp { get; set; }
        public double Link { get; set; }
        public double Lkr { get; set; }
        public double Lrd { get; set; }
        public double Lsl { get; set; }
        public double Ltc { get; set; }
        public double Ltl { get; set; }
        public double Lvl { get; set; }
        public double Lyd { get; set; }
        public double Mad { get; set; }
        public double Mdl { get; set; }
        public double Mga { get; set; }
        public double Mkd { get; set; }
        public double Mmk { get; set; }
        public double Mnt { get; set; }
        public double Mop { get; set; }
        public double Mro { get; set; }
        public double Mtl { get; set; }
        public double Mur { get; set; }
        public double Mvr { get; set; }
        public double Mwk { get; set; }
        public double Mxn { get; set; }
        public double Myr { get; set; }
        public double Mzn { get; set; }
        public double Nad { get; set; }
        public double Ngn { get; set; }
        public double Nio { get; set; }
        public double Nok { get; set; }
        public double Npr { get; set; }
        public double Nzd { get; set; }
        public double Omr { get; set; }
        public double Pab { get; set; }
        public double Pen { get; set; }
        public double Pgk { get; set; }
        public double Php { get; set; }
        public double Pkr { get; set; }
        public double Pln { get; set; }
        public double Pyg { get; set; }
        public double Qar { get; set; }
        public double Rep { get; set; }
        public double Ron { get; set; }
        public double Rsd { get; set; }
        public double Rub { get; set; }
        public double Rwf { get; set; }
        public double Sar { get; set; }
        public double Sbd { get; set; }
        public double Scr { get; set; }
        public double Sek { get; set; }
        public double Sgd { get; set; }
        public double Shp { get; set; }
        public double Sll { get; set; }
        public double Sos { get; set; }
        public double Srd { get; set; }
        public double Ssp { get; set; }
        public double Std { get; set; }
        public double Svc { get; set; }
        public double Szl { get; set; }
        public double Thb { get; set; }
        public double Tjs { get; set; }
        public double Tmt { get; set; }
        public double Tnd { get; set; }
        public double Top { get; set; }
        public double Try { get; set; }
        public double Ttd { get; set; }
        public double Twd { get; set; }
        public double Tzs { get; set; }
        public double Uah { get; set; }
        public double Ugx { get; set; }
        public double Usd { get; set; }
        public double Usdc { get; set; }
        public double Uyu { get; set; }
        public double Uzs { get; set; }
        public double Vef { get; set; }
        public double Ves { get; set; }
        public double Vnd { get; set; }
        public double Vuv { get; set; }
        public double Wst { get; set; }
        public double Xaf { get; set; }
        public double Xag { get; set; }
        public double Xau { get; set; }
        public double Xcd { get; set; }
        public double Xdr { get; set; }
        public double Xlm { get; set; }
        public double Xof { get; set; }
        public double Xpd { get; set; }
        public double Xpf { get; set; }
        public double Xpt { get; set; }
        public double Xrp { get; set; }
        public double Yer { get; set; }
        public double Zar { get; set; }
        public double Zec { get; set; }
        public double Zmk { get; set; }
        public double Zmw { get; set; }
        public double Zrx { get; set; }
        public double Zwl { get; set; }
    }

    public class Data
    {
        public string Currency { get; set; }
        public Rates Rates { get; set; }
    }

    public class Btcrate
    {
        public Data Data { get; set; }
    }
}